// packages/adapters/angular/src/index.ts
import {
  AdapterContext,
  AdapterResult,
  FrameworkAdapter,
  SketchNode,
  registerFrameworkAdapter
} from "@sketchflow/core";

export interface AngularAdapterOptions {
  componentName?: string;
}

const DEFAULT_COMPONENT_NAME = "generated-screen";

const toInlineStyle = (layout: SketchNode["layout"]): string => {
  const styles = [
    `position: absolute`,
    `left: ${layout.x}px`,
    `top: ${layout.y}px`,
    `width: ${layout.width}px`,
    `height: ${layout.height}px`
  ];

  if (typeof layout.rotation === "number") {
    styles.push(`transform: rotate(${layout.rotation}deg)`);
  }

  return styles.join("; ");
};

const indent = (depth: number) => "  ".repeat(depth);

const renderNodes = (nodes: SketchNode[], depth = 3): string => {
  return nodes
    .map((node, index) => {
      const style = toInlineStyle(node.layout);
      const childContent = node.children.length ? `\n${renderNodes(node.children, depth + 1)}\n${indent(depth)}` : "";

      switch (node.type) {
        case "text": {
          const textValue = node.props?.text ?? node.name ?? "Label";
          return `${indent(depth)}<span class="node" style="${style}">${textValue}</span>`;
        }
        case "image": {
          const src = node.props?.src ?? "";
          const alt = node.props?.alt ?? node.name ?? "image";
          return `${indent(depth)}<img class="node" style="${style}" src="${src}" alt="${alt}" />`;
        }
        case "component":
        case "group":
        case "frame":
        default: {
          return `${indent(depth)}<div class="node" style="${style}">${childContent}</div>`;
        }
      }
    })
    .join("\n");
};

const generateAngularComponent = (context: AdapterContext, options: AngularAdapterOptions): AdapterResult => {
  const componentName = options.componentName ?? DEFAULT_COMPONENT_NAME;
  const className = componentName
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
  const templateBody = renderNodes(context.layout);

  const template = `<div class="sketchflow-root" style="position: relative">
${templateBody}
</div>
`;

  const componentTs = `import { Component } from "@angular/core";

@Component({
  selector: "${className}",
  standalone: true,
  templateUrl: "./${componentName}.html",
  styleUrls: ["./${componentName}.css"]
})
export class GeneratedComponent {}
`;

  const componentHtml = template;

  const componentCss = `.sketchflow-root {
  position: relative;
}

.node {
  position: absolute;
}
`;

  return {
    files: [
      { path: `${componentName}.ts`, contents: componentTs },
      { path: `${componentName}.html`, contents: componentHtml },
      { path: `${componentName}.css`, contents: componentCss }
    ]
  } satisfies AdapterResult;
};

export const angularAdapter: FrameworkAdapter = {
  framework: "angular",
  language: "ts",
  introspect: (context: AdapterContext) => ({
    nodeCount: context.layout.length,
    components: context.layout.filter((node) => node.type === "component").length
  }),
  generate: (context: AdapterContext) => {
    const options = (context.options ?? {}) as AngularAdapterOptions;
    return generateAngularComponent(context, options);
  }
};

export const registerAngularAdapter = () => {
  registerFrameworkAdapter(angularAdapter);
  return angularAdapter;
};

// packages/adapters/solid/src/index.ts
import {
  AdapterContext,
  AdapterResult,
  FrameworkAdapter,
  SketchNode,
  registerFrameworkAdapter
} from "@sketchflow/core";

export interface SolidAdapterOptions {
  componentName?: string;
}

const DEFAULT_COMPONENT_NAME = "GeneratedScreen";

const toStyle = (layout: SketchNode["layout"]): string => {
  const rules = [
    `position: "absolute"`,
    `left: ${layout.x}`,
    `top: ${layout.y}`,
    `width: ${layout.width}`,
    `height: ${layout.height}`
  ];

  if (typeof layout.rotation === "number") {
    rules.push(`transform: "rotate(${layout.rotation}deg)"`);
  }

  return `{{ ${rules.join(", ")} }}`;
};

const indent = (depth: number) => " ".repeat(depth);

const renderNodes = (nodes: SketchNode[], depth: number): string => {
  return nodes
    .map((node: SketchNode, index: number) => {
      const key = `${node.id}-${index}`;
      const style = toStyle(node.layout);
      const childContent = node.children.length ? `\n${renderNodes(node.children, depth + 2)}\n${indent(depth)}` : "";

      switch (node.type) {
        case "text": {
          const label = JSON.stringify(node.props?.text ?? node.name ?? "Label");
          return `${indent(depth)}<span data-key="${key}" style=${style}>{${label}}</span>`;
        }
        case "image": {
          const src = JSON.stringify(node.props?.src ?? "");
          const alt = JSON.stringify(node.props?.alt ?? node.name ?? "image");
          return `${indent(depth)}<img data-key="${key}" src=${src} alt=${alt} style=${style} />`;
        }
        case "component":
        case "group":
        case "frame": {
          return `${indent(depth)}<div data-key="${key}" style=${style}>${childContent}</div>`;
        }
        default: {
          return `${indent(depth)}<div data-key="${key}" style=${style} />`;
        }
      }
    })
    .join("\n");
};

const generateSolidComponent = (context: AdapterContext, options: SolidAdapterOptions): AdapterResult => {
  const componentName = options.componentName ?? DEFAULT_COMPONENT_NAME;
  const body = renderNodes(context.layout, 6);

  const contents = `import type { Component } from "solid-js";

export const ${componentName}: Component = () => {
  return (
    <div style={{ position: "relative" }}>
${body}
    </div>
  );
};

export default ${componentName};
`;

  return {
    files: [
      {
        path: `${componentName}.tsx`,
        contents
      }
    ]
  } satisfies AdapterResult;
};

export const solidAdapter: FrameworkAdapter = {
  framework: "solid",
  language: "tsx",
  introspect: (context: AdapterContext) => ({
    nodeCount: context.layout.length,
    components: context.layout.filter((node) => node.type === "component").length
  }),
  generate: (context: AdapterContext) => {
    const options = (context.options ?? {}) as SolidAdapterOptions;
    return generateSolidComponent(context, options);
  }
};

export const registerSolidAdapter = () => {
  registerFrameworkAdapter(solidAdapter);
  return solidAdapter;
};
